language: csharp
mono:
  - nightly
solution: Core2D.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - sudo apt-get install -y gtk-sharp2
  - sudo apt-get install -y monodevelop
  - mono .nuget/nuget.exe restore Core2D.sln -source "https://ci.appveyor.com/nuget/portable-xaml;https://www.nuget.org/api/v2/;https://www.myget.org/F/avalonia-ci/api/v2;https://www.myget.org/F/xamlbehaviors-nightly/api/v2"
  - mono .nuget/nuget.exe install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - mdtool build c:Release Core2D.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./tests/Core2D.UnitTests/bin/Release/Core2D.UnitTests.dll
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./tests/FileSystem.DotNetFx.UnitTests/bin/Release/FileSystem.DotNetFx.UnitTests.dll
